spring:
  application:
    name: Lab3
  datasource:
    url: jdbc:postgresql://localhost:5433/exchange_rate_db
    username: exchange_rate_db_user
    password: master
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

scheduler:
  exchange-rate:
    cron: "0 08 21 * * *"
